name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632cbf8eaa10e17e6a2e10f0c62cda4f7fb70c24

      - name: Set up JDK 11
        uses: actions/setup-java@0ab4596768b603586c0de567f2405c36ca9b5066
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210f55
        with:
          name: build-output
          path: app/build/outputs/