# This is a workflow file to build APK

name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632cbf8eaa10e17e6a2e10f0c62cda4f7fb70c24

      - name: Build APK
        run: |
          echo "Building APK..."

      - name: Upload Artifact
        uses: actions/upload-artifact@f44ae691b2c32385e11205a0e1ff0117a991be4d
        with:
          name: apk
          path: build/outputs/apk/app.apk
